name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Django Application to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |

            cd /home/ubuntu/Sinple_CI_CD_PIPELINE

            git pull origin main

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
