name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Django Application to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          command_timeout: 10m

          script: |

            echo "🚀 Starting Deployment"

            cd /home/ubuntu/Sinple_CI_CD_PIPELINE

            echo "🔄 Syncing repository"
            git fetch origin main
            git reset --hard origin/main

            echo "🐍 Activating virtual environment"
            source venv/bin/activate

            echo "📦 Installing dependencies"
            pip install -r requirements.txt

            echo "🔧 Reloading system services"
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn

            echo "✅ Deployment Completed"
